"""Add images column to chat_messages

Revision ID: 9b3912b7930f
Revises: 
Create Date: 2025-12-29 04:14:28.685020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3912b7930f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add images column (only if it doesn't exist)
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('chat_messages')]
    
    if 'images' not in columns:
        op.add_column('chat_messages', sa.Column('images', sa.JSON(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'images')
    # ### end Alembic commands ###

